# Generated by Django 4.0.3 on 2022-05-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_cultivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivo',
            name='edad',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
