# Generated by Django 4.0.3 on 2022-05-18 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_cultivo_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='edad',
        ),
    ]
